In [4]:
import numpy as np

In [1]:
def solution(n, lost, reserve):
    answer = 0
    return answer

In [60]:
n = 5
lost = [2, 4]
res = [1, 3, 5]

In [67]:
lost = np.array(lost) - 1

res = np.array(res) - 1

tw = np.ones(n)

tw[lost] = tw[lost]- 1

tw[res] = tw[res] + 1

1. 내가 0이면, 앞이랑 비교한다. 앞이 2면 1을 받는다. 앞은 1을 뺀다.
2. 앞이 1이하면, 뒤랑 비교한다. 뒤가 2면 1을 받는다. 뒤는 1을 뺀다.

In [70]:
for i in list(lost):
    try:
        if tw[i-1] == 2:
            tw[i-1] = 1
            tw[i] = 1
        elif tw[i+1] == 2:
            tw[i+1] = 1
            tw[i] = 1
    except:
        pass

In [71]:
tw

array([1., 1., 1., 1., 2.])

In [75]:
tw = np.where(tw >= 1, 1, 0)

In [107]:
n = 5
lost = [2, 4]
res = [1, 3, 5]

In [125]:
n = 5
lost = [2, 4]
res = [3]

In [123]:
def solution(n, lost, reserve):
    import numpy as np
    
    tw = np.ones(n)
    lost = np.array(lost) - 1
    res = np.array(reserve) - 1
    
    tw[lost] -= 1
    tw[res] += 1
    
    for i in lost:
        try:
            if tw[i-1] == 2.:
                tw[i-1] = 1.
                tw[i] = 1.
            elif tw[i+1] == 2.:
                tw[i+1] = 1.
                tw[i] = 1.
        except:
            pass
    
    tw = np.where(tw >= 1., 1., 0)
    answer = np.sum(tw)
    
    return answer

In [124]:
solution(n, lost, res)

5.0

In [132]:
tw[[1, 3]]

array([0., 0.])

In [112]:
n = 5
lost = [2, 4]
res = [1, 3, 5]

In [113]:
tw = np.ones(n)
lost = np.array(lost) - 1
res = np.array(res) - 1

tw[lost] -= 1
tw[res] += 1

In [ ]:
for i in lost:
    try:
        if tw[i-1] == 2:
            tw[i-1] = 1
            tw[i] = 1
        elif tw[i+1] == 2:
            tw[i+1] = 1
            tw[i] = 1
    except:
        pass

tw = np.where(tw >= 1, 1, 0)
answer = np.sum(tw)

In [114]:
tw

array([2., 0., 2., 0., 2.])

In [115]:
lost

array([1, 3])

In [116]:
res

array([0, 2, 4])

In [118]:
list(lost)

[1, 3]

In [120]:
tw[3-1]

2.0