# 다차원 배열 생성하기

In [1]:
import numpy as np

## 직접 원소를 입력해서 다차원 배열 생성하기

np.array()를 사용해 다차원 배열을 생성한다.

In [2]:
boolArray = np.array([True, False, True, False, True])

In [3]:
boolArray

array([ True, False,  True, False,  True])

In [4]:
boolArray.dtype

dtype('bool')

정수형의 default data type은 환경에 따라 다릅니다.

In [5]:
intArray = np.array([[1, 2], [3, 4]])

In [6]:
intArray

array([[1, 2],
       [3, 4]])

In [7]:
intArray.dtype

dtype('int32')

부호 없는 정수형은 uint 입니다.

In [8]:
uintArray = np.array([[1,2], [3, 4]], dtype='uint')

In [9]:
uintArray

array([[1, 2],
       [3, 4]], dtype=uint32)

실수형도 마찬가지입니다.

In [10]:
floatArray = np.array([[1., 2.], [3., 4.]],
                     dtype='float16') #dtype을 지정해줄 수 있다.

In [11]:
floatArray

array([[1., 2.],
       [3., 4.]], dtype=float16)

## ㅇㅇㅇ

### numpy.empty

shape을 정해주면, 아무 값이나 때려박습니다.

In [12]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
np.empty_like(A)

array([[-1074835856,         653, -1074801056],
       [        653, -1074800912,         653],
       [-1074805776,         653,  1965970672]])

empty_like는 형태를 그대로 받아와서 아무 값이나 때려박습니다.

### numpy.zeros

empty랑 비슷한데, 0으로 초기화를 해주는 함수

In [15]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.zeros_like(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

zeros_like는 형태를 받아와서 0으로 초기화

### numpy.ones

zeros랑 비슷한데, 1로 초기화를 해주는 함수

In [17]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.ones_like(A)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

ones_like()도 마찬가지

### numpy.identity

단위행렬을 만들어주는 것입니다.

In [19]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [20]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### numpy.eye

identity의 상위호환, 파라미터를 줘서 값을 바꿀 수 있다.

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [23]:
np.eye(3, 4, 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.eye(3, 4, -1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

하지만 쓸 일이 거의 없다

### numpy.full

zeros와 ones의 상위호환

In [25]:
np.full((2, 3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

하지만 ones를 써서 10을 곱해버리면 되니, 잘 안 쓴다.

### numpy.arange

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

기본적으로 start=0, step=1 이 들어가 있다.

In [27]:
np.arange(start=1, stop=5, step=0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### numpy.linspace

arange랑 비슷한데, 가운데 몇 개를 넣어줄지 정하는 것

In [28]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

## 통계를 해보자

### numpy.amin

최소값을 구해줍니다.

In [29]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.amin(A,
        1) # 축을 의미한다. axis

array([1, 4, 7])

In [31]:
np.amin(A) # 축을 넣지 않으면 전체 값을

1

### numpy.amax

최대값을 구해주겠죠?

In [32]:
np.amax(A,
       0)

array([7, 8, 9])

In [33]:
np.amax(A)

9

### numpy.ptp

최대값과 최소값의 범위를 보는 함수?!

In [34]:
np.ptp(A, 0)

array([6, 6, 6])

In [35]:
np.ptp(A)

8

In [36]:
np.ptp(A, 1)

array([2, 2, 2])

엄청 큰 배열을 살펴볼 때 쓴다.

###  numpy.median

In [37]:
np.median(A, 0)

array([4., 5., 6.])

In [38]:
np.median(A)

5.0

In [39]:
np.median(A, 1)

array([2., 5., 8.])

### numpy.mean

### numpy.var

### numpy.std

## 슬라이싱

In [40]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [41]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
a[0:2, 0:4]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## 인덱싱

In [43]:
a[1]

array([5, 6, 7, 8])

In [44]:
a[0, 1]

2

In [45]:
a[0][1]

2

In [46]:
a[[0, 2], ] # 0, 2행만 가져오기. # 앞에 행 슬라이싱에 리스트로 0,2 값을 줘버리는 것.

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [47]:
a[:, [0,1,3]] # 마찬가지로 0,1,3 열만 가져오기

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

In [48]:
print(a, a.shape, a.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) 2


## 인덱싱과 슬라이싱의 차이

차원을 유지하려면 슬라이싱, 차원을 무시하려면 인덱싱

In [49]:
slicedRow = a[0:1, :]
print(slicedRow, slicedRow.shape, slicedRow.ndim)

[[1 2 3 4]] (1, 4) 2


In [50]:
indexedRow = a[0]
print(indexedRow, indexedRow.shape, indexedRow.ndim)

[1 2 3 4] (4,) 1


In [51]:
indexedRow2 = a[0, :]
print(indexedRow2, indexedRow2.shape, indexedRow2.ndim)

[1 2 3 4] (4,) 1


연산을 할 때는 차원이 같아야 하므로 이렇게 활용한다.

In [52]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 인덱싱과 슬라이싱의 차이2

인덱싱은 값을 복사해서 가져온다.

In [53]:
b = a[0, 0]
b = 100

print("a[0, 0]: {}".format(a[0, 0]))
print("b: {}".format(b))

a[0, 0]: 1
b: 100


In [54]:
c = a[1:3, 1:3]
print(c)

[[ 6  7]
 [10 11]]


슬라이싱은 값을 참조해서 가져온다.

In [55]:
c[0, 0] = 100

print(c)
print('------------------------')
print(a)

[[100   7]
 [ 10  11]]
------------------------
[[  1   2   3   4]
 [  5 100   7   8]
 [  9  10  11  12]]


즉, 슬라이싱은 참조된 값을 바꾸면 원본 값을 바꿔버린다.<br>
반대로 말하면 참조만 하기 때문에 메모리 효율이 좋다.(새로운 변수에 할당하는 게 아니라, 기존 값을 그대로 가져와서 보여주기만 함)

## 불리언 배열 인덱싱

특정 조건을 만족하는 요소를 선택할 수 있다.

In [56]:
a = np.array([[1,2], [3,4], [5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
bool_idx = (a > 2) # 2 보다 큰 값은 True로 반환한다.

bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [58]:
print(a[bool_idx]) # bool_idx를 통해 인덱싱을 하면, True 값만 뱉어낸다.

[3 4 5 6]


In [59]:
print([a[a > 2]]) # 코드를 줄이면 이렇게 된다. 해당 array에서 2 이상의 값만 뱉어내라.

[array([3, 4, 5, 6])]


## 정수 배열 인덱싱

In [60]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
print(a[[0,1,2], [0,1,0]]) # 어려워 보일 수 있다. 그러나 아래를 보자

print(a[[0,1,2],
        [0,1,0]]) # 즉 0,0 =1 을 불러오고, 1,1 = 4 을 불러오고, 2,0 = 5 을 불러오는 것이다.

[1 4 5]
[1 4 5]


## 전치

In [62]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [63]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

## Shape

### reshape

In [64]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
a.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
np.reshape(a, (2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [74]:
np.reshape(a, (1, 6))

array([[1, 2, 3, 4, 5, 6]])

차원이 바뀌지 않게 하는 것이 중요하다.

### ravel

1차원으로 쭉 펴준다.

In [75]:
np.ravel(a)

array([1, 2, 3, 4, 5, 6])

In [76]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

### flatten

np.flatten()  X<br>
np.ndarray.flatten() O<br>
a.flatten() O

객체의 메소드에만 사용 가능하다.

ravel은 뷰를 반환하고, flatten은 복사본을 반환한다.<br>
즉, ravel은 값을 바꾸면 원본 값이 바뀐다.

In [77]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

## 연결

### concatenate

In [79]:
np.concatenate((a, a), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 2],
       [3, 4],
       [5, 6]])

In [80]:
np.concatenate((a, a), axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [5, 6, 5, 6]])

# 다차원 배열 연산

In [81]:
x = np.array([[1., 2.], [3., 4.]])
y = np.array([[5., 6.], [7., 8.]])

In [83]:
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [84]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [85]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [86]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [87]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


### 내적

In [88]:
v = np.array([9, 10])
w = np.array([11, 12])

둘 다 백터가 들어오면 내적

In [89]:
print(v.dot(w))
print(np.dot(v, w))

219
219


행렬과 벡터가 들어오면 곱

In [90]:
print(x.dot(v))
print(np.dot(x, v))

[29. 67.]
[29. 67.]


행렬곱

In [91]:
print(x.dot(y))
print(np.dot(x, y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


# 넘파이 고급

In [94]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x)

In [98]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [99]:
v

array([1, 0, 1])

In [96]:
for i in range(4):
    y[i, :] = x[i, :] + v

In [97]:
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

넘파이의 철학은 반복문을 쓰지 않는 것.

In [101]:
vv = np.tile(v, (4, 1))
vv

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

tile은 말 그대로 tile처럼 쌓는 것.

In [102]:
x + vv

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

그러나 브로드캐스팅이 등장한다면?!

In [103]:
x + v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

넘파이가 tile을 알아서 해준다.