# Chapter 5 pandas 시작하기

In [1]:
# 보통 pandas 를 쓸 때는 pd 로 쓴다.

import pandas as pd
import numpy as np

In [2]:
# Series 와 DataFrame 은 로컬 네임스페이스로 임포트 한다.

from pandas import Series, DataFrame

## 5.1 pandas 자료구조 소개

pandas 는 Series 와 DataFrame 이라는 두 자료구조에 익숙해져야 한다.

그럼 시작해보자.

### 5.1.1 Series

Series는 일련의 객체를 담을 수 있는 1차원 배열 같은 자료구조다.(어떤 Numpy 자료형이라도 담을 수 있다.

그리고 색인(index)라고 하는 배열의 데이터와 연관된 이름을 가지고 있다.

In [3]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
# .values 를 통해서 배열을 알 수 있다.

obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [5]:
# .index 를 통해 색인 객체를 알 수 있다.

obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
# 각각의 데이터를 지칭하는 색인을 지정하여 Series 객체를 생성할 때는 다음과 같다.

obj2 = pd.Series([4, 7, -5, 3], index = ['d', 'b', 'a', 'c'])
obj2
# 좌측에 색인이 보이고, 우측에 데이터가 있다.

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
# Numpy 와 비교하자면 단일 값을 선택하거나 여러 값을 선택할 때 색인으로 라벨을 사용할 수 있다.

obj2['a']

-5

In [8]:
obj2['d'] = 6
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [9]:
# 불리언 배열을 사용해서 값을 걸러 내거나 산술 곱셈을 수행하거나 하는 것도 색인-값 이 그대로 유지 된다.

obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [10]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [11]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [12]:
# Series 를 이해하는 방법은 고정 길이의 정렬된 딕셔너리형이라고 생각하는 것이다.

'b' in obj2

True

In [13]:
'e' in obj2

False

In [14]:
# 아래처럼 딕셔너리를 Series 객체로 만들 수도 있다.

sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [15]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index = states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [16]:
# 누락된 데이터를 찾는 함수다.

pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [17]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [18]:
# isnull 은 Series의 인스턴스 메서드로도 존재한다.

obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [19]:
# Series 의 유용한 기능은 산술 연산에서 색인과 라벨로 자동 정렬하는 것이다.

print(obj3)
print(obj4)
print(obj3+obj4)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64
California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64


In [20]:
# name 속성이 있다.

obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [21]:
#  Series 의 색인은 대입하여 변경할 수 있다.

obj

0    4
1    7
2   -5
3    3
dtype: int64

In [22]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### 5.1.2 DataFrame

- DataFrame은 표 같은 스프레드시트 형식의 자료구조이고 여러 개의 칼럼이 있는데 각 칼럼은 서로 다른 종류의 값을 담을 수 있다.
- DataFrame은 로우와 칼럼에 대한 색인을 가지고 있다.
- 색인의 모양이 같은 Series 객체를 담고 있는 파이썬 사전으로 생각하면 편하다.

In [23]:
data = {'state': ['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
       'year':[2000,2001,2002,2001,2002,2003],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)

In [24]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [25]:
# .head() 메서드를 사용하면 원하는 열 만큼만 추려준다.

frame.head(5)

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [26]:
# 원하는 순서대로 clumns를 지정하면 원하는 순서를 가진 DataFrame 객체가 생성된다.

pd.DataFrame(data, columns = ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [27]:
# Series와 마찬가지로 딕셔너리에 없는 값을 넘기면 결측치로 저장된다.

frame2 = pd.DataFrame(data, columns = ['year', 'state', 'pop', 'debt'],
                     index = ['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [28]:
frame.columns

Index(['state', 'year', 'pop'], dtype='object')

In [29]:
# DataFrame의 컬럼은 Series처럼 사전 형식의 표기버브로 접근하거나 속성 형식으로 접근할 수 있다.

frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [30]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [31]:
# 반환된 Series 객체가 DataFrame과 같은 색인을 가지면 알맞은 값으로 name 속성이 채워진다.
# row 는 위치나 loc 속성을 이용해서 이름을 통해 접근할 수 있다.

frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [32]:
# 컬럼은 대입이 가능하다. 비어 있는 'debt' 컬럼에 스칼라값이나 배열의 값을 대입할 수 있다.

frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [33]:
frame2['debt'] = np.arange(6,)
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [34]:
# 리스트나 배열을 컬럼에 대입할 때는 대입하려는 값의 길이가 DataFrame의 크기와 동일해야 한다.
# Series를 대입하면 DataFrame의 색인에 따라 값이 대입되며 존재하지 않는 색인에는 결측치가 대입된다.

val = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])

frame2['debt'] = val

frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [35]:
# 존재하지 않는 컬럼을 대입하면 새로운 컬럼을 생성한다.
# 파이썬 딕셔너리에서처럼 del 예약어를 사용해서 컬럼을 삭제할 수 있다.

frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [36]:
# del로 삭제해보자

del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [37]:
# 중첩된 딕셔너리를 이용해서 데이터를 생성할 수 있다.

pop = {'Nevada' : {2001: 2.4, 2002: 2.9},
      'Ohio': {2000:1.5, 2001:1.7, 2002:3.6}}

In [38]:
# 이 중첩된 딕셔너리를 DataFrame 에 넘기면 바깥에 있는 사전의 키는 컬럼이 되고, 안에 있는 키는 로우가 된다.

frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [39]:
# Numpy 배열과 유사한 문법으로 데이터를 전치할 수 있다.

frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [40]:
# 색인을 직접 지정하면 지정된 색인으로 DataFrame을 생성한다.

pd.DataFrame(pop, index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [41]:
# Series 객체를 담고 있는 딕셔너리 데이터도 같은 방식으로 취급된다.

pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [42]:
# 만일 데이터프레임의 색인(index) 과 컬럼(columns) 에 name 속성을 지정했다면 이 역시 함께 출력된다.

frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [43]:
# Series 와 유사하게 values 속성은 DataFrame에 저장된 데이터를 2차원 배열로 반환한다.

frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [44]:
# DataFrame의 컬럼이 서로 다른 dtype을 가지고 있다면 모든 컬럼을 수용하기 위해 그 컬럼의 배열의 dtype이 선택된다.

frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### 5.1.3 색인 객체

In [45]:


obj = pd.Series(range(3), index = ['a', 'b', 'c'])
index = obj.index
print(index)
print(index[1:])

Index(['a', 'b', 'c'], dtype='object')
Index(['b', 'c'], dtype='object')


In [46]:
# 색인 객체는 변경이 불가능하다.

#index[1] = 'd'

In [47]:
# 자료구조 사이에서 안전하게 공유될 수 있다.

labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [48]:
obj2 = pd.Series([1.5, -2.5, 0], index = labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [49]:
obj2.index is labels

True

In [50]:
# 또한 배열과 유사하게 Index 객체도 고정 크기로 동작한다.

frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [51]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [52]:
'Ohio' in frame3.columns

True

In [53]:
2003 in frame3.index

False

In [54]:
# 파이썬의 집합과는 달리 pandas 의 인덱스는 중복되는 값을 허용한다.

dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

색인 메서드와 속성

- append : 추가적인 색인 객체를 덧붙여 새로운 색인을 반환한다.
- difference : 색인의 차집합을 반환한다.
- intersection : 색인의 교집합을 반환한다.
- union : 색인의 합집합을 반홚나다.
- isin : 색인이 넘겨받은 색인에 존재하는지 알려주는 불리언 배열을 반환한다.
- delete : i 위치의 색인이 삭제된 새로운 색인을 반환한다.
- drop : 넘겨받은 값이 삭제된 새로운 색인을 반환한다.
- insert : i 위치에 색인이 추가된 새로운 색인을 반환한다.
- is_monotonic : 색인이 단조성을 가진다면 True를 반환한다.
- is_unique : 중복되는 색인이 없다면 True를 반환한다.
- unique : 색인에서 중복되는 요소를 제거하고 유일한 값만 반환한다.

## 5.2 핵심기능

### 5.2.1 재색인

In [55]:
# pandas 객체의 중요한 기능 중 하나는 reindex 이다. 새로운 색인에 맞도록 객체를 새로 생성한다.

obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [56]:
# 이 Series 객체에 대해 reindex를 호출하면 데이터를 새로운 색인에 맞게 재배열하고, 존재하지 않는 색인값이 있다면 NaN을 추가한다.

obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [57]:
# 시계열 같은 순차적 데이터를 재색인할 때는 method 옵션을 이용해서 해결하며, ffill 같은 메서드를 이용해 누락된 값을 채운다.

obj3 = pd.Series(['blue', 'purple', 'yellow'], index = [0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [58]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [59]:
# DataFrame에 대한 reindex는 row, column 또는 둘 다 변경 가능하다. 그냥 순서만 전달하면 row가 재색인 된다.

frame = pd.DataFrame(np.arange(9).reshape(3,3),
                    index = ['a', 'c', 'd'],
                    columns = ['순천', '여수', '광양'])
frame

순천  여수  광양
a   0   1   2
c   3   4   5
d   6   7   8

In [60]:
frame2 = frame.reindex(['a', 'b', 'c','d'])
frame2

순천   여수   광양
a  0.0  1.0  2.0
b  NaN  NaN  NaN
c  3.0  4.0  5.0
d  6.0  7.0  8.0

In [61]:
# column 은 columns 예약어를 통해서 재색인할 수 있다.

states = ['순천', '여수', '광양']

frame.reindex(columns = states)

순천  여수  광양
a   0   1   2
c   3   4   5
d   6   7   8

In [62]:
frame.loc[['a', 'b', 'c', 'd'], states]

C:\Users\thinp\Anaconda3\lib\site-packages\pandas\core\indexing.py:1494: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


순천   여수   광양
a  0.0  1.0  2.0
b  NaN  NaN  NaN
c  3.0  4.0  5.0
d  6.0  7.0  8.0

### 5.2.2 하나의 row 나 column 삭제하기

In [63]:
obj = pd.Series(np.arange(5.), index = ['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [64]:
# drop 메서드를 통해서 선택한 값들이 삭제된 새로운 객체를 얻을 수 있다.

new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [65]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [66]:
# DataFrame 에서는 row와 column 모두에서 값을 삭제할 수 있다.

data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index = ['순천', '여수', '광양', '곡성'],
                   columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
순천    0    1      2     3
여수    4    5      6     7
광양    8    9     10    11
곡성   12   13     14    15

In [67]:
# drop 함수에 인자로 row 이름을 넘기면 해당 row(axis 0) 의 값을 모두 삭제한다.

data.drop(['여수', '순천'])

one  two  three  four
광양    8    9     10    11
곡성   12   13     14    15

In [68]:
# column을 삭제할 때는 axis=1 또는 axis=columns 를 인자로 넘겨주면 된다.

data.drop('two', axis=1)

one  three  four
순천    0      2     3
여수    4      6     7
광양    8     10    11
곡성   12     14    15

In [69]:
data.drop(['two', 'four'], axis = 'columns')

one  three
순천    0      2
여수    4      6
광양    8     10
곡성   12     14

In [70]:
# drop 함수처럼 Series 나 DataFrame의 크기 또는 형태를 변경하는 함수는 새로운 객체를 반환하는 대신 원본 객체를 변경한다.

# inplace 옵션을 사용하면 버려지는 값을 모두 삭제하므로 주의해서 사용하자.
obj.drop('c', inplace = True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### 5.2.3 색인하기, 선택하기, 거르기

In [71]:
# Series의 색인 (obj[...])은 Numpy 배열의 색인과 유사하게 동작하지만 정수가 아니어도 된다는 점이 다르다.

obj = pd.Series(np.arange(4.), index = ['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [72]:
obj['b']

1.0

In [73]:
obj[1]

1.0

In [74]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [75]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [76]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [77]:
obj[obj>2]

d    3.0
dtype: float64

In [78]:
# label 이름으로 슬라이싱하면 시작점과 끝점을 포함한다는 것이 일반 파이썬에서의 슬라이싱과 다른 점이다.

obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [79]:
# 슬라이싱 문법으로 선택된 영역에 값을 대입하는 것은 생각하는 대로 동작한다.

obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [80]:
# 색인으로 DataFrame 에서 하나 이상의 컬럼 값을 가져올 수 있다.

data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['순천', '여수', '광양', '곡성'],
                   columns = ['one', 'two','three', 'four'])
data

one  two  three  four
순천    0    1      2     3
여수    4    5      6     7
광양    8    9     10    11
곡성   12   13     14    15

In [81]:
data['two']

순천     1
여수     5
광양     9
곡성    13
Name: two, dtype: int32

In [82]:
data[['three', 'one']]

three  one
순천      2    0
여수      6    4
광양     10    8
곡성     14   12

In [83]:
# 슬라이싱으로 row를 선택하거나 불리언 boolean 배열로 row를 선택할 수 있다.

data[:2]

one  two  three  four
순천    0    1      2     3
여수    4    5      6     7

In [84]:
data[data['three']>5]

one  two  three  four
여수    4    5      6     7
광양    8    9     10    11
곡성   12   13     14    15

In [85]:
data >5

one    two  three   four
순천  False  False  False  False
여수  False  False   True   True
광양   True   True   True   True
곡성   True   True   True   True

#### loc과 iloc 으로 선택하기

DataFrame의 로우에 대한 라벨로 색인하는 방법으로 특수한 색인 필드인 loc와 iloc 을 소개한다.

축 이름을 선택할 때는 loc을

정수 색인으로 선택할 때는 iloc을 사용한다.

In [86]:
data.loc['순천', ['two', 'three']]

two      1
three    2
Name: 순천, dtype: int32

In [87]:
# iloc 을 이용하면 정수 색인으로도 위와 비슷하게 선택할 수 있다.

data.iloc[2, [3,0,1]]

four    11
one      8
two      9
Name: 광양, dtype: int32

In [88]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: 광양, dtype: int32

In [89]:
data.iloc[[1,2], [3,0,1]]

four  one  two
여수     7    4    5
광양    11    8    9

In [90]:
# 이 두 함수는 슬라이스도 지원할 뿐더러 단일 라벨이나 라벨 리스트도 지원한다.

data.loc[:'광양', 'two']

순천    1
여수    5
광양    9
Name: two, dtype: int32

In [91]:
data.iloc[:, :3][data.three > 5]

one  two  three
여수    4    5      6
광양    8    9     10
곡성   12   13     14

DataFrame 의 값 선택하기

- df[val] : DataFrame에서 하나의 칼럼 또는 여러 칼럼을 선택한다
- df.loc[val] : 라벨값으로 row의 부분집합을 선택한다.
- df.loc[:, val] : 라벨값으로 column의 부분집합을 선택한다.
- df.loc[val1, val2] : 라벨값으로 row 와 column의 부분집합을 선택한다.


- df.iloc[where] : 정수 색인으로 row의 부분집합을 선택한다.
- df.iloc[:, where] : 정수 색인으로 column의 부분집합을 선택한다.
- df.iloc[where_i, where_j] : 정수 색인으로 row와 column의 부분집합을 선택한다.


- df.at[label_i, label_j] : row와 column의 라벨로 단일 값을 선택한다.
- df.iat[i, j] : row와 column의 정수 색인으로 단일 값을 선택한다.


- reindex 메서드 : 하나 이상의 축을 새로운 색인으로 맞춘다.
- get_value, set_value 메서드 : row 나 column 이름으로 DataFrame의 값을 선택한다.

### 5.2.4 정수 색인

In [92]:
# 정수 색인으로 pandas 객체를 다루다보면 리스트나 튜플 같은 파이썬 내장 자료구조에서 색인을 다루는 방법과의 차이점 때문에
# 실수하게 되는 경우가 있다. 다음의 예를 보자.

ser = pd.Series(np.arange(3.))
#ser[-1]


KeyError: -1

In [93]:
# 이 경우 pandas 는 라벨 색인을 찾는 데 실패하므로 정수 색인으로 값을 찾는다.
# 하지만 라벨 색인이 0,1,2 를 포함하는 경우 사용자가 라벨 색인으로 선택하려는 것인지 정수 색인으로 선택하려는 것인지 모른다.

# 반면 정수색인을 사용하지 않는 경우 이런 모호함은 사라진다.

ser2 = pd.Series(np.arange(3.), index = ['a', 'b', 'c'])
ser2[-1]

2.0

In [94]:
# 정숫값을 담고 있는 축 색인이 있다면 우선적으로 라벨을 먼저 찾아보도록 구현되어 있다.
# 좀 더 세밀하게 사용하고 싶다면
# 라벨은 loc 함수로, 정수 색인에 대해서는 iloc 함수를 사용하자.

ser[:1]

0    0.0
dtype: float64

In [95]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [96]:
ser.iloc[:1]

0    0.0
dtype: float64

### 5.2.5 산술 연산과 데이터 정렬

In [97]:
# pandas 에서 중요한 기능 중 하나는 다른 색인을 가지고 있는 객체 간의 산술 연산이다.
# 객체를 더할 때 짝이 맞지 않는 색인이 있다면 결과에 두 색인이 통합된다.
# 데이터베이스의 조인과 유사하게 작동한다고 볼 수 있다.

s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index = ['a','c', 'd', 'e'])

s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a','c','e','f','g'])

print(s1)
print("------------")
print(s2)

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64
------------
a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64


In [98]:
# 서로 겹치는 색인이 없는 경우 데이터는 NA 값이 된다.

s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [99]:
# DataFrame의 경우 정렬은 row와 column 모두에 적용된다.

df1 = pd.DataFrame(np.arange(9).reshape((3,3)), columns = list('bcd'), index= ['순천', '여수', '광양'])
df2 = pd.DataFrame(np.arange(12).reshape((4,3)), columns = list('bde'), index= ['김해', '순천', '여수', '창원'])

print(df1)
print("-----------------")
print(df2)

    b  c  d
순천  0  1  2
여수  3  4  5
광양  6  7  8
-----------------
    b   d   e
김해  0   1   2
순천  3   4   5
여수  6   7   8
창원  9  10  11


In [100]:
df1+ df2

b   c     d   e
광양  NaN NaN   NaN NaN
김해  NaN NaN   NaN NaN
순천  3.0 NaN   6.0 NaN
여수  9.0 NaN  12.0 NaN
창원  NaN NaN   NaN NaN

In [101]:
# 공통되는 column label 이나 row label 이 없는 DataFrame 을 더하면 결과에 아무것도 나타지 않을 것이다.

df1 = pd.DataFrame({'A':[1,2]})
df2 = pd.DataFrame({'B':[3,4]})

print(df1)
print("----------------")
print(df2)

   A
0  1
1  2
----------------
   B
0  3
1  4


In [102]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

#### 산술 연산 메서드에 채워 넣을 값 지정하기

In [103]:
# 서로 다른 색인을 가지는 객체 간의 산술 연산에서 존재하지 않는 축의 값을 특수한 값으로 지정하고 싶을 때

df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns = list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns = list('abcde'))

df2.loc[1, 'b'] = np.nan

print(df1)
print("----------------------------")
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
----------------------------
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [104]:
# 둘을 더하면 겹치지 않는 부분은 NA 값이 된다.

df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [105]:
# df1 에 add 메서드를 사용하고, df2 와 fill_value 값을 인자로 전달한다.

df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [106]:
# 각각의 산술 연산 메서드는 r로 시작하는 계산 인자를 뒤집어 계산하는 짝궁 메서드를 가진다.

1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [107]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [108]:
# Series나 DataFrame을 재색인할 때도 fill_value를 지정할 수 있다.

df1.reindex(columns = df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

산술 연산 메서드

- add, radd
- sub, rsub
- div, rdiv
- floordiv, rfloordiv : 소수점 내림(//)연산을 위한 메서드
- mul, rmul
- pow, rpow : 멱승(**)을 위한 메서드

#### DataFrame과 Series 간의 연산

다른 차원의 NumPy 배열과의 연산처럼 DataFrame과 Series 간의 연산도 잘 정의되어 있다.

In [109]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [110]:
arr[0]

array([0., 1., 2., 3.])

In [111]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [112]:
# 위의 코드를 보면 arr 에서 arr[0]을 빼면 계산은 각 로우에 대해 한 번씩만 수행된다.
# 이를 브로드 캐스팅이라고 한다.
# DataFrame 과 Series 간의 연산은 이와 유사하다.

frame = pd.DataFrame(np.arange(12.).reshape((4,3)), columns = list('bde'), index = ['순천', '여수', '광양', '곡성'])

series = frame.iloc[0]

print(frame)
print("---------------")
print(series)

      b     d     e
순천  0.0   1.0   2.0
여수  3.0   4.0   5.0
광양  6.0   7.0   8.0
곡성  9.0  10.0  11.0
---------------
b    0.0
d    1.0
e    2.0
Name: 순천, dtype: float64


In [113]:
# 기본적으로 DataFrame과 Series 간의 산술 연산은
# Series의 색인을 DataFrame의 column에 맞추고 아래 row로 전파한다.

frame - series

b    d    e
순천  0.0  0.0  0.0
여수  3.0  3.0  3.0
광양  6.0  6.0  6.0
곡성  9.0  9.0  9.0

In [114]:
# 만약 색인값을 DataFrame의 column이나 Series의 색인에서 찾을 수 없다면
# 그 객체는 형식을 맞추기 위해 재색인 된다.

series2 = pd.Series(np.arange(3), index = ['b', 'e', 'f'])

frame + series2

b   d     e   f
순천  0.0 NaN   3.0 NaN
여수  3.0 NaN   6.0 NaN
광양  6.0 NaN   9.0 NaN
곡성  9.0 NaN  12.0 NaN

In [115]:
# 만약 각 row 에 대해 연산을 수행하고 싶다면 산술 연산 메서드를 사용하면 된다.

series3 = frame['d']
frame

b     d     e
순천  0.0   1.0   2.0
여수  3.0   4.0   5.0
광양  6.0   7.0   8.0
곡성  9.0  10.0  11.0

In [116]:
series3

순천     1.0
여수     4.0
광양     7.0
곡성    10.0
Name: d, dtype: float64

In [117]:
# 인자로 넘기는 axis 값은 연산을 적용할 축 번호다. axis='index' 나 axis=0 은 DataFrame의 row를 따라 연산ㄴ을 수행하라는 의미다.

frame.sub(series3, axis = 'index')

b    d    e
순천 -1.0  0.0  1.0
여수 -1.0  0.0  1.0
광양 -1.0  0.0  1.0
곡성 -1.0  0.0  1.0

#### 5.2.6 함수 적용과 매핑

In [118]:
# pandas 객체에도 Numpy의 유니버설 함수(배열의 각 원소에 적용되는 메서드)를 적용할 수 있다.

frame = pd.DataFrame(np.random.randn(4,3), columns = list('bde'), index=['순천', '여수', '광양', '곡성'])

frame

b         d         e
순천  0.662042  0.330823 -1.928062
여수 -0.385994 -1.118396  0.132950
광양 -0.382506  2.300098 -0.397887
곡성  1.085791  0.479451  0.759144

In [119]:
np.abs(frame) #abs 는 절댓값을 반환해주는 내장함수다.

b         d         e
순천  0.662042  0.330823  1.928062
여수  0.385994  1.118396  0.132950
광양  0.382506  2.300098  0.397887
곡성  1.085791  0.479451  0.759144

In [120]:
# 자주 사용되는 또 다른 연산은 각 컬럼이나 로우의 1차원 배열에 함수를 적용하는 것이다.
# DataFrame 의 apply 메서드를 이용해 수행할 수 있다.

f = lambda x : x.max() - x.min()

frame.apply(f)

# 여기서 함수 f는 Series의 최댓값과 최솟값의 차이를 계산하느 함수다.
# frame 의 각 column 에 대해 한 번만 수행되며 결괏값은 계산을 적용한 column을 색인으로 하는 Series를 반환한다.

b    1.471785
d    3.418494
e    2.687205
dtype: float64

In [121]:
# apply 함수에 axis = 'columns' 인자를 넘기면 각 row 에 대해 한 번씩만 수행된다.

frame.apply(f, axis='columns')

순천    2.590104
여수    1.251346
광양    2.697985
곡성    0.606340
dtype: float64

In [122]:
# 배열에 대한 일반적인 통계(sum 이나 mean같은)는 DataFrame 의 메서드로 존재하므로 apply 메서드를 사용할 필요 없다.

def f(x):
    return pd.Series([x.min(), x.max()], index = ['min', 'max'])

frame.apply(f)

b         d         e
min -0.385994 -1.118396 -1.928062
max  1.085791  2.300098  0.759144

In [123]:
# 배열에 각 원소에 적용되는 파이썬의 함수를 사용할 수도 있다.
# frame 객체에서 실숫값을 문자열 포맷으로 변환하고 싶다면 applymap을 이용해서 다음과 같이 할 수 있다.

format = lambda x: '%.2f' % x

frame.applymap(format)
# 이 메서드의 이름이 applymap인 이유는 Series는 각 원소에 적용할 함수를 지정하기 위한 map메서드를 가지고 있기 때문이다.

b      d      e
순천   0.66   0.33  -1.93
여수  -0.39  -1.12   0.13
광양  -0.38   2.30  -0.40
곡성   1.09   0.48   0.76

In [124]:
frame['e'].map(format)

순천    -1.93
여수     0.13
광양    -0.40
곡성     0.76
Name: e, dtype: object

### 5.2.7 정렬과 순위

In [3]:
# row 나 column의 색인을 알파벳순으로 정렬하려면 새로운 객체를 반환하는 sort_index 메서드를 사용하면 된다.

obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [4]:
# DataFrame은 row나 column중 하나의 축을 기준으로 정렬할 수 있다.

frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    index=['three', 'one'],
                    columns=['d', 'a', 'b', 'c'])

frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [5]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [6]:
# 데이터는 기본적으로 오름차순으로 내림차순으로 정렬된다.

frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [7]:
# Series 객체를 값에 따라 정렬하고 싶다면 sort_values 메서드를 사용하면 된다.

obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [8]:
# 결측값은 기본적으로 Series객체에서 가장 마지막에 위치한다.

obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [9]:
# DataFrame 에서 하나 이상의 column에 있는 값으로 정렬을 하는 경우 sort_values 함수의 by 옵션에 하나 이상의 column을 넘긴다.

frame = pd.DataFrame({'b':[4,7,-3,2], 'a':[0,1,0,1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [10]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [11]:
# 여러개의 column을 정렬하려면 column 이름이 담긴 list를 전달하면 된다.

frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [12]:
# 순위는 정렬과 거의 흡사한데, 1부터 배열의 유효한 데이터 개수까지 순서를 매긴다.
# 기본적으로 Series 와 DataFrame의 rank 메서드는 동점인 항목에 대해서는 평균 순위를 매긴다.

obj= pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [13]:
# 데이터 상에서 나타나는 순서에 따라 순위를 매길 수도 있다.

obj.rank(method = 'first')

# 여기서는 평균 순위를 적용하지 않고 먼저 출현한 순서대로 순위를 주었다.

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [14]:
# 내림차순으로 매길 수도 있다.

obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [15]:
# DataFrame 에서는 row나 column에 대해 순위를 정할 수 있다.

frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                     'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [16]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

순위의 동률을 처리하는 메서드

- 'average' : 기본값. 같은 값을 가지는 항목들의 평균값을 순위로 삼는다.
- 'min' : 같은 값을 가지는 그룹을 낮은 순위로 매긴다.
- 'max' : 같은 값을 가지는 그룹을 높은 순위로 매긴다.
- 'first' : 데이터 내의 위치에 따라 순위를 매긴다.
- 'dense' : method='min' 과 같지만 같은 그룹 내에서 모두 같은 순위를 적용하지 않고 1씩 증가시킨다.

### 5.2.8 중복색인

중복된 색인값을 가지는 Series 객체를 살펴보자.

In [17]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [18]:
# 중복되는 색인 값을 찾는다. 

obj.index.is_unique

False

In [19]:
obj['a']

a    0
a    1
dtype: int64

In [20]:
obj['c']

4

In [21]:
# DataFrame에서 row를 선택하는 것도 동일하다.

df = pd.DataFrame(np.random.randn(4,3), index = ['a', 'a', 'b', 'b'])
df

0         1         2
a  0.821424 -2.793877 -1.196781
a  1.687758  0.677722 -0.625166
b -0.823163 -1.006863  1.969760
b  0.169462  0.044101  0.046460

In [22]:
df.loc['b']

0         1        2
b -0.823163 -1.006863  1.96976
b  0.169462  0.044101  0.04646

## 5.3 기술 통계 계산과 요약

pandas 객체는 일반적인 수학 메서드와 통계 메서드를 가지고 있다.

In [23]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],[np.nan, np.nan], [0.75, -1.3]],
                 index = ['a', 'b', 'c', 'd'],
                 columns = ['one', 'two'])

df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [24]:
# DataFrame 의 sum 메서드를 호출하면 각 column의 합을 담은 Series를 반환한다.

df.sum()

one    9.25
two   -5.80
dtype: float64

In [25]:
# axis='columns' 또는 axis=1 옵션을 넘기면 각 컬럼의 합을 반환한다.

df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [26]:
# 전체 row 나 column 이 NA가 아니라면 NA값은 제외되고 계산된다.
# 이는 skipna 옵션으로 조정할 수 있다.

df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

축소 메서드의 옵션

- axis : 연산을 수행할 축. DataFrame 에서 0은 row고 1은 column이다.
- skipna : 누락된 값을 제외할 것인지 정하는 옵션. 기본값은 True
- level : 계산하려는 축이 계층적 색인(다중 색인) 이라면 레벨에 따라 묶어서 계산한다.

In [27]:
# idxmin 이나 idxmax 같은 메서드는 최솟값 혹은 최댓값은 가지고 있는 색인값과 같은 간접통계를 반환한다.

df.idxmax()

one    b
two    d
dtype: object

In [28]:
# 또 다른 메서드로 누산(accumulation)dl dlTek.

df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [29]:
# 축소나 누산이 아닌 다른 종류의 메서드로 describe가 있다.

df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [30]:
# 수치 데이터가 아닐 경우 describe는 다른 요약 통계를 생성한다.

obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

요약 통계 관련 메서드

- count : NA 값을 제외한 값의 수를 반환한다.
- describe : Series나 DataFrame 의 각 column에 대한 요약 통계를 계산한다.
- min, max : 최솟값과 최댓값을 계산한다.
- argmin, argmax : 각각 최솟값과 최댓값을 담고 있는 색인의 위치(정수)를 반환한다.
- idxmin, idxmax : 각각 최솟값과 최댓값을 담고 있는 색인의 값을 반환한다.
- quantile : 0부터 1까지의 분위수를 계산한다.
- sum
- mean
- median
- mad : 평균값에서 평균절대편차를 계산한다.
- prod : 모든 값의 곱
- var : 분산
- std : 표준편차

### 5.3.1 상관관계와 공분산

In [32]:
conda install pandas-datareader

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\thinp\Anaconda3

  added / updated specs:
    - pandas-datareader


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.8.2                |           py37_0         3.1 MB
    conda-package-handling-1.3.11|           py37_0         280 KB
    pandas-datareader-0.8.1    |             py_0          71 KB
    ------------------------------------------------------------
                                           Total:         3.4 MB

The following NEW packages will be INSTALLED:

  conda-package-han~ pkgs/main/win-64::conda-package-handling-1.3.11-py37_0
  pandas-datareader  pkgs/main/noarch::pandas-datareader-0.8.1-py_0

The following packages will be UPDATED:

  conda                                       4.6.11-py37_0 --> 4.8.2-py37_0




pandas-datareader-0. | 71 KB     |            |   0%

'ET'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.


In [34]:
# 주가 정보를 다운 받자.

import pandas_datareader.data as web

all_data = {ticker: web.get_data_yahoo(ticker)
           for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [35]:
returns = price.pct_change()
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2020-03-02  0.093101  0.031886  0.066539  0.037168
2020-03-03 -0.031759 -0.040209 -0.047919 -0.034353
2020-03-04  0.046385  0.041272  0.036715  0.033644
2020-03-05 -0.032437 -0.034794 -0.025095 -0.048669
2020-03-06 -0.013280 -0.014049 -0.028267 -0.015640

In [36]:
# corr 메서드는 NA가 아니며 정렬된 색인에서 연속하는 두 Series에 대해 상관관계를 계산하고
# cov 메서드는 공분산을 계산한다.

returns['MSFT'].corr(returns['IBM'])

0.4865607125552544

In [37]:
returns['MSFT'].cov(returns['IBM'])

9.654035862318893e-05

In [38]:
# MSFT는 파이썬 속성 이름 규칙에 어긋나지 않으므로 좀 더 편리한 문법으로 해당 column을 선택할 수 있다.

returns.MSFT.corr(returns.IBM)

0.4865607125552544

In [39]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.415777  0.608832  0.555795
IBM   0.415777  1.000000  0.486561  0.427708
MSFT  0.608832  0.486561  1.000000  0.686713
GOOG  0.555795  0.427708  0.686713  1.000000

In [40]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000257  0.000089  0.000146  0.000137
IBM   0.000089  0.000177  0.000097  0.000087
MSFT  0.000146  0.000097  0.000222  0.000157
GOOG  0.000137  0.000087  0.000157  0.000235

In [41]:
# DataFrame의 corrwith 메서드를 사용하면 다른 Series나 DataFrame의 상관관계를 계산한다.

returns.corrwith(returns.IBM)

AAPL    0.415777
IBM     1.000000
MSFT    0.486561
GOOG    0.427708
dtype: float64

In [42]:
returns.corrwith(volume)

AAPL   -0.146561
IBM    -0.095097
MSFT   -0.050246
GOOG   -0.028704
dtype: float64

### 5.3.2 유일값, 값 세기, 멤버십

In [43]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [44]:
# unques()  는 중복되는 값을 제거하고 유일값만 반환한다.

uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [45]:
# 정렬된 순서대로 반환하고 싶으면 uniques.sort() 를 이용해서 나중에 정렬할 수 있다.
# value_counts 메서드는 도수를 계산하여 반환한다.

obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [46]:
pd.value_counts(obj.values, sort=False)

b    2
a    3
c    3
d    1
dtype: int64

In [47]:
# isin 메서드는 어떤 값이 존재하는지 boolean 벡터를 반환한다.

obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [48]:
mask = obj.isin(['b','c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [50]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [51]:
# isin 과 관련이 있는 Index.get_indexer 메서드는 여러 값이 들어 있는 배열에서 유일한 값의 색인 배열을 구할 수 있다.

to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

unique_vals = pd.Series(['c', 'b', 'a'])

pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)