# chapter 3 내장 자료구조, 함수, 파일

## 3.1 자료구조와 순차 자료형

### 3.1.1 튜플

튜플은 1차원의 고정된 크기를 가지는 변경 불가능한 순차 자료형이다.
튜플을 생성하는 가장 쉬운 방법은 쉼표로 구분된 값을 대입하는 것이다.

In [1]:
tup = 4, 5, 6

In [2]:
tup

(4, 5, 6)

In [3]:
nested_tup = (4, 5, 6), (7, 8)

In [4]:
nested_tup

((4, 5, 6), (7, 8))

In [5]:
tuple([4, 0, 2])

(4, 0, 2)

In [6]:
tup = tuple('string')

In [7]:
tup

('s', 't', 'r', 'i', 'n', 'g')

In [8]:
tup[0]

's'

In [11]:
tup = tuple(['foo', [1, 2], True])

In [12]:
tup

('foo', [1, 2], True)

In [13]:
tup[2]

True

In [14]:
tup[1].append(3)

In [15]:
tup

('foo', [1, 2, 3], True)

In [16]:
(4, None, 'foo') + (6, 0) + ('bar',)

(4, None, 'foo', 6, 0, 'bar')

In [17]:
('foo', 'bar') * 4

('foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'bar')

튜플에서 값 분리하기

In [18]:
tup = (4, 5, 6)

In [19]:
a, b, c = tup

In [20]:
b

5

In [21]:
tup = 4, 5, (6, 7)

In [22]:
a, b, (c, d)= tup

In [23]:
d

7

In [24]:
a, b = 1, 2

In [25]:
a

1

In [26]:
b

2

In [27]:
b, a = a, b

In [28]:
a

2

In [29]:
b

1

In [30]:
seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]

In [31]:
for a, b, c in seq :
    print('a = {0}, b = {1}, c = {2}'.format(a, b, c))

a = 1, b = 2, c = 3
a = 4, b = 5, c = 6
a = 7, b = 8, c = 9


In [34]:
values = 1, 2, 3, 4, 5

In [35]:
a, b, *rest = values

In [36]:
a, b

(1, 2)

In [37]:
rest

[3, 4, 5]

In [38]:
a, b, *_ = values

In [39]:
values

(1, 2, 3, 4, 5)

튜플 메서드

In [40]:
a = (1, 2, 2, 2, 3, 4, 2)

In [41]:
a.count(2)

4

### 3.1.2 리스트

튜플과는 대조적으로 리스트는 크기나 내용의 변경이 가능하다.

In [42]:
a_list = [2, 3, 7, None]

In [43]:
tup = ('foo', 'bar', 'baz')

In [44]:
b_list = list(tup)

In [45]:
b_list

['foo', 'bar', 'baz']

In [47]:
b_list[1] = 'peekaboo'

In [48]:
b_list

['foo', 'peekaboo', 'baz']

In [49]:
gen = range(10)

In [50]:
gen

range(0, 10)

In [51]:
list(gen)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

원소 추가하고 삭제하기 append, insert, remove

In [62]:
# append 메서드를 통해서 리스트의 끝에 새로운 값을 추가할 수 있다.
b_list.append('dwarf')

In [53]:
b_list

['foo', 'peekaboo', 'baz', 'dwarf']

In [54]:
# insert 메서드는 특정 위치에 값을 추가한다.
b_list.insert(1, 'red')

In [55]:
b_list

['foo', 'red', 'peekaboo', 'baz', 'dwarf']

In [56]:
# insert 메서드의 반대 개념으로 pop 메서드가 있다. 특정 위치의 값을 반환하면서 해당 값을 리스트에서 삭제한다.
b_list.pop(2)

'peekaboo'

In [57]:
b_list

['foo', 'red', 'baz', 'dwarf']

In [58]:
b_list.append('foo')

In [59]:
b_list

['foo', 'red', 'baz', 'dwarf', 'foo']

In [60]:
# remove 메서드를 활용해서 원소를 삭제할 수 있다. 단, 삭제는 제일 앞에 위치한 값부터 이루어진다.
b_list.remove('foo')

In [61]:
b_list

['red', 'baz', 'dwarf', 'foo']

In [63]:
# in 예약어를 사용해서 리스트에 어떤 값이 있는지 검사할 수 있다.
'dwarf' in b_list

True

In [65]:
# not 예약어를 사용해서 in 예약어의 반대 의미로 사용할 수도 있다.
'dwarf' not in b_list

False

리스트 이어붙이기

In [66]:
[4, None, 'foo'] + [7, 8, (2, 3)]

[4, None, 'foo', 7, 8, (2, 3)]

In [70]:
# 만일 리스트를 미리 정의해두었다면 extend 메서드를 사용해서 여러 개의 값을 추가할 수 있다.
# 리스트를 이어붙이면 새로운 리스트를 생성하고 값을 복사하게 되므로 상대적으로 연산비용이 높음
# 큰 리스트일수록 extend 메서를 사용하는 것이 나은 선택
x = [4, None, 'foo']

In [68]:
x.extend([7, 8, (2, 3)])

In [69]:
x

[4, None, 'foo', 7, 8, (2, 3)]

정렬

In [71]:
# sort 함수를 이용해서 새로운 리스트를 정렬할 수 있다.
a = [7, 2, 5, 1, 3]

In [72]:
a.sort()

In [73]:
a

[1, 2, 3, 5, 7]

In [75]:
# sort는 편의를 위해 몇가지 옵션 제공. 
b = ['saw', 'small', 'He', 'foxes', 'six']

In [76]:
b.sort(key=len)

In [77]:
b

['He', 'saw', 'six', 'small', 'foxes']

이진 탐색과 정렬된 리스트 유지하기

In [79]:
# bisect.bisect 메서드는 값이 추가될 때 리스트가 정렬된 상태를 유지할 수 있는 위치를 반환
# bisect.insort 는 실제로 정렬된 상태를 유지한 채 값을 추가
import bisect
c = [1, 2, 2, 2, 3, 4, 7]

In [81]:
bisect.bisect(c, 2)

4

In [82]:
bisect.bisect(c, 5)

6

In [83]:
bisect.insort(c, 6)

In [84]:
c

[1, 2, 2, 2, 3, 4, 6, 7]

슬라이싱

In [85]:
# 리스트와 같은 자료형(배열, 튜플, ndarray)은 색인 연산자 [] 안에 start:stop 을 지정해서 원하는 크기만큼 잘라낼 수 있다.
seq = [7, 2, 3, 7, 5, 6, 0, 1]

In [86]:
seq[1:5]

[2, 3, 7, 5]

In [87]:
seq[3:4] = [6, 3]

In [88]:
seq

[7, 2, 3, 6, 3, 5, 6, 0, 1]

In [90]:
# 색인의 시작 위치에 있는 값은 포함되지만 끝 위치에 있는 값은 포함되지 않는다.
# 따라서 슬라이싱 결과의 개수는 stop - start 이다.
# 색인의 시작값이나 끝값은 생략할 수 있다. 순차자료형의 처음이나 마지막이 된다.
seq[:5]

[7, 2, 3, 6, 3]

In [91]:
seq[3:]

[6, 3, 5, 6, 0, 1]

In [92]:
# 음수색인은 순차 자료형의 끝에서부터의 위치를 나타낸다.
seq[-4:]

[5, 6, 0, 1]

In [93]:
seq[-6:-2]

[6, 3, 5, 6]

In [94]:
# 두 번째 콜론 다음에 간격을 지정할 수 있다. 다음과 같다.
seq[::2]

[7, 3, 3, 6, 1]

In [95]:
# 간격 값으로 -1을 사용하면 리스트나 튜플을 역순으로 반환한다.
seq[::-1]

[1, 0, 6, 5, 3, 6, 3, 2, 7]

### 3.1.3 내장 순차 자료형 함수

enumerate

In [96]:
# 이 함수는 순차 자료형에서 현재 아이템의 색인을 함께 처리하고자 할 때 흔히 사용한다.
some_list = ['foo', 'bar', 'baz']
mapping = {}
for i, v in enumerate(some_list):
    mapping[v] = i

In [97]:
mapping

{'foo': 0, 'bar': 1, 'baz': 2}

sorted

In [98]:
# sorted 함수는 정렬된 새로운 순차 자료형을 반환한다.
sorted([7, 1, 2, 6, 0, 3, 2])

[0, 1, 2, 2, 3, 6, 7]

In [99]:
sorted('horse race')

[' ', 'a', 'c', 'e', 'e', 'h', 'o', 'r', 'r', 's']

zip

In [100]:
# zip 함수는 여러개의 리스트나 튜플 또는 다른 순차 자료형을 서로 짝지어서 튜플의 리스트를 생성한다.
seq1 = ['foo', 'bar', 'baz']

In [101]:
seq2 = ['one', 'two', 'three']

In [103]:
zipped = zip(seq1, seq2)
list(zipped)

[('foo', 'one'), ('bar', 'two'), ('baz', 'three')]

In [105]:
# zip 함수는 여러 개의 순차 자료형을 받을 수 있으며 반환되는 리스트의 크기는 넘겨받은 순차자료형 중 가장 짧은 크기로 정해진다.
seq3 = [False, True]
list (zip(seq1, seq2, seq3))

[('foo', 'one', False), ('bar', 'two', True)]

In [106]:
# zip 함수의 아주 흔한 사용 예는 여러 개의 순차 자료형을 동시에 순회하는 경우인데, enumerate 와 함께 사용되기도 한다.
for i, (a, b) in enumerate(zip(seq1, seq2)):
    print('{0}: {1}, {2}'.format(i, a, b))

0: foo, one
1: bar, two
2: baz, three


In [109]:
# zip 함수를 사용해서 짝지어진 순차 자료형을 다시 풀어낼 수도 있다. 이를 이용해서 리스트의 row를 column으로 변환하는 것도 가능
pitchers = [('Nolan', 'Ryan'), ('Roger', 'Clemens'), ('Schilling', 'Curt')]
first_names, last_names = zip(*pitchers)
print(first_names)
print(last_names)

('Nolan', 'Roger', 'Schilling')
('Ryan', 'Clemens', 'Curt')


reversed

In [110]:
# reversed 는 순차 자료형을 역순으로 순회한다.
list(reversed(range(10)))

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

### 3.1.4 사전, 딕셔너리

In [111]:
# dict 은 파이썬 내장 자료구조 중에서 가장 중요하대. 일반적으로는 해시맵, 연관 배열 이라고 알려져 있대. 사전은 유연한 크기를 가지는
# 키-값 쌍으로 키와 값 모두 파이썬 객체래. 생성방법은 중괄호 {} 를 사용하고 콜론으로 구분된 키와 값을 둘러 싸는 것이래.

emtpy_dict={}
d1 = {'a' : 'some value', 'b' : [1, 2, 3, 4]}
d1

{'a': 'some value', 'b': [1, 2, 3, 4]}

In [113]:
d1[7] = 'an integer'

In [114]:
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}

In [115]:
d1['b']

[1, 2, 3, 4]

In [116]:
# in 예약어 사용 가능
'b' in d1

True

In [117]:
# del 예약어나 pop 메서드를 사용해서 사전의 값을 삭제할 수 있다.
d1[5] = 'some value'
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer', 5: 'some value'}

In [118]:
d1['dummy'] = 'another value'
d1

{'a': 'some value',
 'b': [1, 2, 3, 4],
 7: 'an integer',
 5: 'some value',
 'dummy': 'another value'}

In [119]:
del d1[5]

In [120]:
d1

{'a': 'some value',
 'b': [1, 2, 3, 4],
 7: 'an integer',
 'dummy': 'another value'}

In [121]:
ret = d1.pop('dummy')
ret

'another value'

In [122]:
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}

In [123]:
# keys와 values 메서드는 각각 키와 값이 담긴 이터레이터를 반환한다. 키-값 쌍은 일정한 기준으로 정렬되어 있지 않지만
# keys 메서드와 values 메서드에서 반환하는 리스트는 같은 순서를 가진다.

list(d1.keys())

['a', 'b', 7]

In [124]:
list(d1.values())

['some value', [1, 2, 3, 4], 'an integer']

In [125]:
# update 메서드를 사용해서 하나의 사전을 다른 사전과 합칠 수 있다.
d1.update({'b': 'foo', 'c': 12})
d1

# update 메서드는 사전 값을 그 자리에서 바꾸므로 이미 존재하는 키에 대해 update를 호출하면 이전 값은 사라진다.

{'a': 'some value', 'b': 'foo', 7: 'an integer', 'c': 12}

순차 자료형에서 사전 생성하기

In [129]:
mapping = dict(zip(range(5), reversed(range(5))))

In [130]:
mapping

{0: 4, 1: 3, 2: 2, 3: 1, 4: 0}

기본값

In [132]:
words = ['apple', 'bat', 'bar', 'atom', 'book']

In [133]:
by_letter = {}

In [135]:
for word in words:
    letter = word[0]
    if letter not in by_letter:
        by_letter[letter] = [word]
    else:
        by_letter[letter].append(word)

In [136]:
by_letter

{'a': ['apple', 'apple', 'atom'], 'b': ['bat', 'bat', 'bar', 'book']}

In [139]:
by_letter = {}

In [140]:
for word in words:
    letter = word[0]
    by_letter.setdefault(letter, []).append(word)

In [141]:
by_letter

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}

유효한 사전 키

In [142]:
# 사전의 값으로 어떤 파이썬 객체라도 가능하지만 키는 스칼라형, 튜플처럼 바뀌지 않는 객체만 가능
# 기술적으로는 해시 가능 해야 한다는 뜻이다.
# hash 함수를 사용해서 검사할 수 있다.
hash('string')

-323267583385353780

In [143]:
hash((1, 2, (2, 3)))

1097636502276347782

In [146]:
hash((1, 2, [2, 3]))
# list는 변경이 가능한 값이므로 해시 가능하지 않음

TypeError: unhashable type: 'list'

In [147]:
#리스트를 키로 사용하기 위한 한 가지 방법은 리스트를 튜플로 변경하는 것
d = {}
d[tuple([1, 2, 3])] = 5
d

{(1, 2, 3): 5}

### 3.1.5 집합

In [148]:
#집합은 유일한 원소만 담는 정렬되지 않는 자료형. 사전과 유사하지만 키만 가지고 있다고 보면 된다.
# set 함수나, 중괄호를 이용한다.

set([2, 2, 2, 1, 3, 3])

{1, 2, 3}

In [149]:
{2, 2, 2, 1, 3, 3,}

{1, 2, 3}

In [150]:
# 집합은 합집함, 교집합, 차집합, 대칭차집합 같은 산술 집합 연산을 제공한다.
# 다음 주 집합을 union 메서드를 사용하여 모아보겠다. | 이항연산자도 사용 가능

a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7, 8}

In [151]:
a.union(b)

{1, 2, 3, 4, 5, 6, 7, 8}

In [152]:
a | b

{1, 2, 3, 4, 5, 6, 7, 8}

In [153]:
# 교집합은 intersection 메서드를 사용하거나 & 이항연산자를 쓰자

a.intersection(b)

{3, 4, 5}

In [154]:
a & b

{3, 4, 5}

In [156]:
# 일반적인 집합 메서드를 정리해주마
# a.add(x) - 대체 없음 - a에 원소 x를 추가
# a.clear() - 대체 없음 - 모든 원소를 제거하고 빈 상태로 되돌림.
# a.remove(x) - 대체 없음 - a에서 원소 x를 제거
# a.pop() - 대체 없음 - a에서 임의의 원소를 제거한다. 비어 있는 경우 Key Error 를 발생시킨다.
# a.union(b) - a | b - a와 b의 합집합
# a.update(b) - a |= b - a에 a와 b의 합집합을 대입한다.
# a.intersection(b) - a & b - a와 b의 교집합
# a.intersection_update(b) - a &= b - a에 a와 b의 교집합을 대입한다.
# a.difference(b) - a - b - a와 b의 차집합
# a.difference_update(b) - a -= b - a에 a와 b의 차집합을 대입한다.
# a.symmetric_difference(b) - a ^ b - a와 b의 대칭차집합
# a.symmetric_difference_update(b) - a ^= b - a에 a와 b의 대칭차집합을 대입한다.
# a.issubset(b) - NA - a의 모든 원소가 b에 속할 경우 True 반환
# a.issuperset(b) - NA - a가 b의 모든 원소를 포함할 경우 True 반환
# a.isdisjoint(b) - NA - a와 b 모두에 속하는 원소가 없을 경우 True 반환

In [157]:
c = a.copy()

In [158]:
c |=b

In [159]:
c

{1, 2, 3, 4, 5, 6, 7, 8}

In [160]:
d = a.copy()

In [161]:
d &= b
d

{3, 4, 5}

In [162]:
#사전처럼 집합 원소들도 일반적으로 변경이 불가능해야 한다. 리스트 같은 원소를 담으려면 튜플로 변경해야 한다.

my_data = [1, 2, 3, 4]
my_set = {tuple(my_data)}

In [163]:
my_set

{(1, 2, 3, 4)}

In [164]:
a_set = {1, 2, 3, 4, 5}

In [165]:
{1, 2, 3}.issubset(a_set)

True

In [166]:
a_set.issuperset({1, 2, 3})

True

In [167]:
{1, 2, 3} == {3, 2, 1}

True

### 3.1.6 리스트, 집합, 딕셔너리 표기법

In [168]:
# 리스트 표기법은 파이썬 언어에서 가장 사랑받는 기능 중 하나. 이를 활용하면 간결한 표현으로 새로운 리스트 제작 가능
# [expr for val in collection if condition]
# 이게 기본 형식이래 뭔지 모르겠다 증말
# 이걸 반복문으로 구현한 게 이거래

result = []
for val in collection:
    if condition:
        result.append(expr)

NameError: name 'collection' is not defined

In [169]:
strings = ['a', 'as', 'bat', 'car', 'dove', 'python']
[x.upper() for x in strings if len(x) > 2]

['BAT', 'CAR', 'DOVE', 'PYTHON']

In [171]:
# 뭐라고 하는데 뭐라는지 모르겠다. 일단 코드를 쳐본다.

unique_lengths = {len(x) for x in strings}
unique_lengths

{1, 2, 3, 4, 6}

In [172]:
# map 함수를 이용해서 함수적으로 표현할 수도 있단다.

set(map(len, strings))

{1, 2, 3, 4, 6}

In [173]:
# 리스트에서 문자열의 위치를 담고 있는 사전을 생성해보자.

loc_mapping = {val : index for index, val in enumerate(strings)}
loc_mapping

{'a': 0, 'as': 1, 'bat': 2, 'car': 3, 'dove': 4, 'python': 5}

중첩된 리스트 표기법

In [174]:
# 다음과 같은 데이터가 있다.

all_data = [['John', 'Emily', 'Michael', 'Mary', 'Steven'], ['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']]

# 각 이름에서 e 가 2개 이상 포함된 이름의 목록을 구한다고 가정하자. 리스트는 for문을 통해서 구한다.

In [176]:
names_of_interest = []
for names in all_data:
    enough_es = [name for name in names if name.count('e') >=2]
    names_of_interest.extend(enough_es)
    
names_of_interest

['Steven']

In [177]:
# 이걸 중첩된 리스트 표기법으로 구해본단다.

result = [name for names in all_data for name in names
         if name.count('e') >= 2]

result

['Steven']

In [178]:
# 되게 어렵게 느껴진다. 튜플을 리스트로 변환하는 식을 해보자.

some_tuples = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
flattened = [x for tup in some_tuples for x in tup]
flattened

[1, 2, 3, 4, 5, 6, 7, 8, 9]

## 3.2 함수

In [179]:
# 함수는 def 예약어로 정의하고 return 예약어를 사용해서 값을 반환한다.

def my_function(x, y, z=1.5):
    if z >1 :
        return z * (x + y)
    else:
        return z / (x + y)

In [181]:
my_function(5,6,z=0.7)

0.06363636363636363

### 3.2.1 네임스페이스, 스코프, 지역함수

In [182]:
# 함수년 전역과 지역, 두 가지 스코프에서 변수를 참조한다네. 변수의 스코프를 네임스페이스라고 부른대.

def func():
    a = []
    for i in range (5):
        a.append(i)

In [184]:
a = []
def func():
    for i in range(5):
        a.append(i)

In [185]:
a = None

In [186]:
def bind_a_variable():
    global a
    a = []

bind_a_variable()
print(a)

[]


### 3.2.2 여러 값 반환하기

In [187]:
# 파이썬은 자바와 C++과는 다르게 하나의 함수에서 여러 개의 값을 반환할 수 있다. 살펴보자

def f():
    a = 5
    b = 6
    c = 7
    return a, b, c

a, b, c = f()

In [188]:
return_value = f()

### 3.2.3 함수도 객체다

In [197]:
states = ['Alabama', 'Georgia!', 'Georgia', 'georgia', 'Fl0rIda', 'southcarolina##', 'West virginia?']

In [200]:
# 이런 엉망인 데이터를 내장 문자열 메서드와 정규 표현식을 통해서 쉽게 해결한다.

import re

def clean_strings(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub('[!#?]','',value)
        value = value.title()
        result.append(value)
    return result

In [201]:
clean_strings(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Fl0Rida',
 'Southcarolina',
 'West Virginia']

In [202]:
# 다른 유용한 접근법으로는 적용할 함수를 리스트에 담아두고 각각의 문자열에 적용하는 것이다.

def remove_punctuation(value):
    return re.sub('[!#?]', '' , value)

clean_ops = [str.strip, remove_punctuation, str.title]

def clean_stings(strings, ops):
    result = []
    for value in strings:
        for function in ops:
            value = function(value)
        result.append(value)
    return result

In [203]:
clean_strings(states, clean_ops)

TypeError: clean_strings() takes 1 positional argument but 2 were given

In [204]:
for x in map(remove_punctuation, states):
    print(x)

Alabama
Georgia
Georgia
georgia
Fl0rIda
southcarolina
West virginia


### 3.2.4 익명 함수

In [205]:
# 파이썬은 익명 함수 혹은 람다 함수라고 하는 값을 반환하는 단순한 한 문장으로 이루어진 함수를 지원
# lambda 예약어로 정의하며, 이는 익명함수를 선언한다 라는 의미다.

def short_function(x):
    return x *2

equiv_ann = lambda x: x*2

In [206]:
# 람다함수는 데이터 분석에서 특히 편하다고 한다. 왜인지는 모르겠다.

strings = ['foo', 'card', 'bar', 'aaaa','abab']

In [208]:
strings.sort(key=lambda x : len(set(list(x))))

# 람다 함수가 익명 함수라고 불리는 이유 중 하나는 이 함수 객체에는 명시적은 __name__ 속성이 없기 때문이다.

In [209]:
strings

['aaaa', 'foo', 'abab', 'bar', 'card']

### 3.2.5 커링 : 일부 인자만 취하기

In [ ]:
# 커링은 사람 이름에서 따온 암튼 뭔 용어인데, 함수에서 일부 인자만 취하는 새로운 함수를 만드는 기법이라고 한다.

### 3.2.6 제너레이터

In [210]:
# 리스트 내의 객체나 파일의 각 로우 같은 순차적인 자료를 순회하는 일관적인 방법을 제공하는데,
# 이터레이터 프로토콜을 통해 순회 가능한 객체를 만들 수 있다.
# 예를 들어 사전을 순회하면 사전의 키가 반환된다.

some_dict = {'a':1, 'b':2, 'c':3}

In [211]:
for key in some_dict:
    print(key)

a
b
c


In [212]:
dict_iterator = iter(some_dict)

In [213]:
dict_iterator

In [214]:
list(dict_iterator)

['a', 'b', 'c']

In [215]:
# 제너레이터는 단일 값을 반환하지 않고 순차적으로 값을 매 요청시마다 하나씩 반환한다.
# 함수에서 return 대신에 yield 예약어를 사용한다.

def squares(n=10):
    print ('Generating squares from 1 to {0}'.format (n ** 2))
    for i in range(1, n+1 ):
        yield i **2

In [217]:
gen = squares()

In [218]:
# 제너레이터를 호출하더라도 코드가 즉각적으로 실행되지 않는다.
gen

<generator object squares at 0x0000021476D48750>

In [219]:
# 값을 요청하면 그때서야 제너레이터의 코드가 실행된다.
for x in gen:
    print(x, end= ' ')

Generating squares from 1 to 100
1 4 9 16 25 36 49 64 81 100 

제너레이터 표현식

In [220]:
# 제너레이터 표현식을 써보자.

gen = ( x ** 2 for x in range(100))
gen

<generator object <genexpr> at 0x0000021476D486D8>

In [221]:
sum(x **2 for x in range(100))

328350

In [222]:
dict((i, i **2 ) for i in range(5))

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

itertools 모듈

In [223]:
# 그냥 뭔말인지 모르겠고 예제를 보자

import itertools

In [224]:
first_letter = lambda x: x[0]

In [225]:
names = ['Alan', 'Adam', 'Wes', 'Will', 'Albert', 'Steven']

In [226]:
for letter, names in itertools.groupby(names, first_letter):
    print(letter, list(names)) #names 는 제너레이터래

A ['Alan', 'Adam']
W ['Wes', 'Will']
A ['Albert']
S ['Steven']


# chapter 4 Numpy

## 4.1 Numpy ndarray : 다차원 배열 객체

In [4]:
import numpy as np

In [2]:
data = np.random.randn(2, 3)
data

array([[ 0.63718558, -0.01474821,  0.41369519],
       [-0.4266787 ,  0.33118644,  0.53310465]])

In [3]:
data*10

array([[ 6.3718558 , -0.14748211,  4.13695193],
       [-4.26678698,  3.31186445,  5.33104653]])

In [4]:
data + data

array([[ 1.27437116, -0.02949642,  0.82739039],
       [-0.8533574 ,  0.66237289,  1.06620931]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

### 4.1.1. ndarray 생성하기

In [20]:
# 배열을 생성하는 가장 쉬운 방법은 array 함수를 이용하는 것.

data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [21]:
# 같은 길이를 가지는 리스트를 내포하고 있는 순차 데이터는 다차원 배열로 변환 가능

data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
# ndim, shape 속성을 검사해서 확인

arr2.ndim

2

In [23]:
arr2.shape

(2, 4)

In [12]:
# zeros, ones 를 통해서 0과 1이 들어 있는 배열을 생성.

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 4.1.2 ndarray의 dtype

In [24]:
# dtype 은 ndarray 가 메모리에 있는 특정 데이터를 해석하기 위해 필요한 정보를 담고 있는 특수한 객체이다.

arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)

In [25]:
arr1.dtype

dtype('float64')

In [26]:
arr2.dtype

dtype('int32')

In [27]:
# astype 메서드는 dtype 를 다른 형으로 명시적으로 변환(캐스팅) 가능하다.

arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [28]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [29]:
# 정수형을 부동소수점으로 변환했다. 정수형으로 변환하면 소수점 아래 자리는 버려진다.

arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [30]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [31]:
arr.dtype

dtype('float64')

In [33]:
# 숫자형식의 문자열을 담고 있는 배열이 있다면 astype 을 사용하여 숫자로 변환 가능

numeric_strings = np.array (['1.25', '-9.6', '42'], dtype = np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [35]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [46]:
arr = np.array([1,2,3,4,5,6])
arr * arr


array([ 1,  4,  9, 16, 25, 36])

In [50]:
arr = np.arange(10)

In [51]:
arr_slice = arr[5:8]
arr_slice[1] = 222
arr

array([  0,   1,   2,   3,   4,   5, 222,   7,   8,   9])

In [56]:
arr2 = np.array([[1,2,3],[4,5,6,],[7,8,9]])
arr2[:2,1:]

array([[2, 3],
       [5, 6]])

In [5]:
arr3d = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [6]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
old_values = arr3d[0].copy()

In [8]:
arr3d[0] = 42

In [9]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
arr3d[0] = old_values
arr3d


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
arr3d[1,0]

array([7, 8, 9])

In [12]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [13]:
x[0]

array([7, 8, 9])